# Data exploration

In [1]:
from src import preprocessing as ppr

### Initial exploration

With pandas, we need to have openpyxl installed to read an .xlsx file

In [ ]:
dataset_list = ppr.read_dataset()

# To show the stats of all the datasets
for i,dataset in enumerate(dataset_list):
        print(f"                      {'='*20} DATASET {i+1} {'='*20}")
        print(f"Shape: {dataset.shape}")
        display(dataset.describe(include='all').loc[['count', 'unique']])

                      ==================== DATASET 1 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,999,1000,48,9,1,599,61,1000,NaN,NaN

                      ==================== DATASET 2 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,998,1000,50,10,1,621,61,1000,NaN,NaN

                      ==================== DATASET 3 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,999,1000,49,11,1,614,61,1000,NaN,NaN

                      ==================== DATASET 4 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,999,1000,49,11,1,623,61,1000,NaN,NaN

                      ==================== DATASET 5 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,998,998,51,8,1,614,61,998,NaN,NaN

                      ==================== DATASET 6 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,1000,1000,47,9,1,590,61,1000,NaN,NaN

                      ==================== DATASET 7 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,999,1000,51,9,1,615,61,1000,NaN,NaN

                      ==================== DATASET 8 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,999,1000,53,10,1,626,61,1000,NaN,NaN

                      ==================== DATASET 9 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,997,1000,50,10,1,593,61,1000,NaN,NaN

                      ==================== DATASET 10 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,999,0.0,0.0
unique,NaN,1000,1000,48,10,1,630,60,999,NaN,NaN

                      ==================== DATASET 11 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,999,999,49,9,1,624,61,999,NaN,NaN

                      ==================== DATASET 12 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,998,1000,45,9,1,621,61,1000,NaN,NaN

                      ==================== DATASET 13 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,998,1000,46,10,1,605,61,1000,NaN,NaN

                      ==================== DATASET 14 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,999,1000,50,10,1,618,61,722,NaN,NaN

                      ==================== DATASET 15 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,997,1000,50,8,1,617,61,1000,NaN,NaN

                      ==================== DATASET 16 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,1000,1000,48,10,1,603,61,1000,NaN,NaN

                      ==================== DATASET 17 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,999,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,997,1000,47,10,1,600,61,1000,NaN,NaN

                      ==================== DATASET 18 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,1000,1000,47,11,1,621,61,795,NaN,NaN

                      ==================== DATASET 19 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,1000,1000,49,10,1,631,61,1000,NaN,NaN

                      ==================== DATASET 20 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,999,1000,49,9,1,633,61,1000,NaN,NaN

                      ==================== DATASET 21 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,1000,1000,49,11,1,599,61,1000,NaN,NaN

                      ==================== DATASET 22 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,999,1000,47,8,1,610,61,1000,NaN,NaN

                      ==================== DATASET 23 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,1000,1000,48,8,1,632,61,1000,NaN,NaN

                      ==================== DATASET 24 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,1000,1000,49,11,1,603,61,1000,NaN,NaN

                      ==================== DATASET 25 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,104.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,1000,1000,29,8,2,231,45,382,NaN,NaN

                      ==================== DATASET 26 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,0.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,999,1000,2,1,1,422,59,1000,NaN,NaN

                      ==================== DATASET 27 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,0.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,1000,1000,1,1,1,106,4,1000,NaN,NaN

                      ==================== DATASET 28 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,0.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,1000,1000,1,1,1,188,12,1000,NaN,NaN

                      ==================== DATASET 29 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,0.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,997,999,4,1,1,637,61,999,NaN,NaN

                      ==================== DATASET 30 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,0.0,1000,1000,1000,1000,1000,1000,1000,999,0.0,0.0
unique,NaN,997,1000,7,1,1,750,61,998,NaN,NaN

                      ==================== DATASET 31 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,0.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,997,1000,8,2,1,528,61,1000,NaN,NaN

                      ==================== DATASET 32 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,0.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,995,1000,9,2,1,627,61,1000,NaN,NaN

                      ==================== DATASET 33 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,0.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,995,999,13,2,1,695,61,999,NaN,NaN

                      ==================== DATASET 34 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,0.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,990,996,23,4,1,717,61,996,NaN,NaN

                      ==================== DATASET 35 ====================
Shape: (435, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,0.0,435,435,435,435,435,435,435,435,435,431
unique,NaN,431,435,20,7,1,369,61,435,435,431

In [3]:
df = ppr.fusion_dataset(dataset_list)
print(f"Shape: {df.shape}")
display(df.describe(include='all').loc[['count', 'unique']])

Shape: (34435, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,24104.0,34434,34435,34435,34435,34435,34435,34435,34433,435,431
unique,NaN,33569,34377,56,13,2,1815,61,33264,435,431

In [8]:
print(f"            Train dataset")
print(f"Number of review : {len(df[df["type"]=="train"])}\n")
print(f"Average of star : {df[df["type"]=="train"]["note"].mean()}\n")
print(f"Number of non-empty review : \n{df[df["type"]=="train"].count()}\n")


print(f"            Test dataset")
print(f"Number of review : {len(df[df["type"]=="test"])}")
print(f"Average of star : {df[df["type"]=="test"]["note"].mean()}\n")
print(f"Number of non-empty review : \n{df[df["type"]=="test"].count()}\n")

            Train dataset
Number of review : 24104

Average of star : 2.8476186525058083

Number of non-empty review :
note                24104
auteur              24103
avis                24104
assureur            24104
produit             24104
type                24104
date_publication    24104
date_exp            24104
avis_en             24103
avis_cor                0
avis_cor_en             0
dtype: int64

            Test dataset
Number of review : 10331
Average of star : nan

Number of non-empty review :
note                    0
auteur              10331
avis                10331
assureur            10331
produit             10331
type                10331
date_publication    10331
date_exp            10331
avis_en             10330
avis_cor              435
avis_cor_en           431
dtype: int64

In [15]:
print(f"Train : Number of review per {df[df["type"]=="train"]['assureur'].value_counts()}\n")
print(f"Test : Number of review per {df[df["type"]=="test"]['assureur'].value_counts()}\n")

Train : Number of review per assureur
Direct Assurance        5896
L'olivier Assurance     4288
APRIL Moto              1023
GMF                      997
Néoliane Santé           861
MACIF                    829
AMV                      688
Santiane                 658
AXA                      629
MAAF                     612
MAIF                     591
Allianz                  574
Pacifica                 553
Matmut                   474
MGP                      446
Active Assurances        403
Ag2r La Mondiale         350
Harmonie Mutuelle        312
Eurofil                  289
APRIL                    283
Mercer                   267
Cardif                   265
Zen'Up                   245
Cegema Assurances        214
Génération               212
Mgen                     209
CNP Assurances           147
Crédit Mutuel            146
Afer                     144
SwissLife                138
Eca Assurances           132
Mutuelle des Motards     128
Generali                 128
Assur O'Poil             110
Groupama                  97
SantéVet                  96
Sogessur                  96
Sogecap                   72
Intériale                 63
MetLife                   53
Assur Bon Plan            51
Euro-Assurance            43
Malakoff Humanis          38
Gan                       33
Carac                     32
Peyrac Assurances         28
Suravenir                 27
Afi Esca                  26
AssurOnline               25
Solly Azar                25
Magnolia                  19
LCL                       18
Mapa                      10
Sma                        6
MMA                        4
Hiscox                     1
Name: count, dtype: int64

Test : Number of review per assureur
Direct Assurance        2607
L'olivier Assurance     1792
GMF                      475
APRIL Moto               452
MACIF                    366
Néoliane Santé           356
AMV                      308
Santiane                 295
MAAF                     269
AXA                      264
Allianz                  251
MAIF                     235
Pacifica                 223
Matmut                   203
MGP                      191
Ag2r La Mondiale         168
Active Assurances        163
Eurofil                  142
Cardif                   115
Harmonie Mutuelle        113
APRIL                    109
Mercer                   105
Cegema Assurances         98
Mgen                      96
Zen'Up                    92
Génération                80
Afer                      80
Eca Assurances            59
Mutuelle des Motards      52
Crédit Mutuel             47
Sogessur                  46
Groupama                  46
SwissLife                 46
CNP Assurances            46
Generali                  45
Assur O'Poil              45
SantéVet                  34
Sogecap                   26
MetLife                   24
Assur Bon Plan            24
Gan                       20
Intériale                 18
Euro-Assurance            17
AssurOnline               11
Malakoff Humanis          11
Carac                     11
Afi Esca                  10
LCL                        9
Suravenir                  8
Peyrac Assurances          7
Solly Azar                 7
Magnolia                   6
MMA                        3
Hiscox                     2
Mapa                       2
Sma                        1
Name: count, dtype: int64

In [ ]:
print(f"Train : number of review per {df[df["type"]=="train"]['produit'].value_counts()}\n")
print(f"Test : number of review per {df[df["type"]=="test"]['produit'].value_counts()}\n")

Train : number of review per produit
auto                                     14076
sante                                     3525
moto                                      2105
habitation                                1956
prevoyance                                 791
credit                                     653
vie                                        578
animaux                                    374
multirisque-professionnelle                 20
garantie-decennale                          12
assurances-professionnelles                  8
responsabilite-civile-professionnelle        5
flotte-automobile                            1
Name: count, dtype: int64

### Data Cleaning

In [19]:
df[df["type"]=="train"].head(10)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
0,5.0,brahim--k-131532,"Meilleurs assurances, prix, solutions, écoute,...",Direct Assurance,auto,train,06/09/2021,01/09/2021,"Best insurance, price, solutions, listening, s...",NaN,NaN
1,4.0,bernard-g-112497,"je suis globalement satisfait , sauf que vous ...",Direct Assurance,auto,train,03/05/2021,01/05/2021,"I am generally satisfied, except that you have...",NaN,NaN
2,5.0,virginie-t-107352,Prix tres abordable plusieurs options s'offren...,Direct Assurance,auto,train,21/03/2021,01/03/2021,Very affordable price Several options are avai...,NaN,NaN
3,4.0,boulain-f-116580,"je satisfait du service, une réponse très rapi...",L'olivier Assurance,auto,train,10/06/2021,01/06/2021,"I satisfy the service, a very fast response fr...",NaN,NaN
4,1.0,ouaille31-51798,"Client depuis plus de 25 ans, très déçu de cet...",Matmut,auto,train,29/01/2017,01/01/2017,"Customer for more than 25 years, very disappoi...",NaN,NaN
5,1.0,spam-62064,"Vente forcée par téléphone, prétextant des évè...",Néoliane Santé,sante,train,06/03/2018,01/03/2018,"Forced sale by phone, claiming serious events ...",NaN,NaN
6,3.0,ludovic-b-135966,Nouveau client satisfait du prix et des servic...,APRIL,sante,train,05/10/2021,01/10/2021,New customer satisfied with the price and serv...,NaN,NaN
7,1.0,laetitia741-97523,Un assureur m'a contacté par telephone pour me...,SantéVet,animaux,train,17/09/2020,01/09/2020,An insurer contacted me by phone to sell me th...,NaN,NaN
8,1.0,gbernard10-102485,Je ne peux que rejoindre les nombreux avis nég...,Mercer,sante,train,12/01/2021,01/01/2021,I can only join the many negative opinions. I ...,NaN,NaN
9,1.0,rezo31-62544,GENERALI ASSURANCES VIE PATRIMOINE Très mauvai...,Generali,vie,train,21/03/2018,01/03/2018,Generali Insurance life heritage very bad cust...,NaN,NaN

### Visualization

### Conclusion

My conclusion

# Next