# Data exploration

In [1]:
from src import preprocessing as ppr

### Initial exploration

With pandas, we need to have openpyxl installed to read an .xlsx file

In [6]:
dataset_list = ppr.read_dataset()

# To show the stats of all the dataset
for i,dataset in enumerate(dataset_list):
        print(f"                      {'='*20} DATASET {i+1} {'='*20}")
        print(f"Shape: {dataset.shape}")
        display(dataset.describe(include='all').loc[['count', 'unique']])

                      ==================== DATASET 1 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,999,1000,48,9,1,599,61,1000,NaN,NaN

                      ==================== DATASET 2 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,998,1000,50,10,1,621,61,1000,NaN,NaN

                      ==================== DATASET 3 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,999,1000,49,11,1,614,61,1000,NaN,NaN

                      ==================== DATASET 4 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,999,1000,49,11,1,623,61,1000,NaN,NaN

                      ==================== DATASET 5 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,998,998,51,8,1,614,61,998,NaN,NaN

                      ==================== DATASET 6 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,1000,1000,47,9,1,590,61,1000,NaN,NaN

                      ==================== DATASET 7 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,999,1000,51,9,1,615,61,1000,NaN,NaN

                      ==================== DATASET 8 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,999,1000,53,10,1,626,61,1000,NaN,NaN

                      ==================== DATASET 9 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,997,1000,50,10,1,593,61,1000,NaN,NaN

                      ==================== DATASET 10 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,999,0.0,0.0
unique,NaN,1000,1000,48,10,1,630,60,999,NaN,NaN

                      ==================== DATASET 11 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,999,999,49,9,1,624,61,999,NaN,NaN

                      ==================== DATASET 12 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,998,1000,45,9,1,621,61,1000,NaN,NaN

                      ==================== DATASET 13 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,998,1000,46,10,1,605,61,1000,NaN,NaN

                      ==================== DATASET 14 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,999,1000,50,10,1,618,61,722,NaN,NaN

                      ==================== DATASET 15 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,997,1000,50,8,1,617,61,1000,NaN,NaN

                      ==================== DATASET 16 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,1000,1000,48,10,1,603,61,1000,NaN,NaN

                      ==================== DATASET 17 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,999,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,997,1000,47,10,1,600,61,1000,NaN,NaN

                      ==================== DATASET 18 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,1000,1000,47,11,1,621,61,795,NaN,NaN

                      ==================== DATASET 19 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,1000,1000,49,10,1,631,61,1000,NaN,NaN

                      ==================== DATASET 20 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,999,1000,49,9,1,633,61,1000,NaN,NaN

                      ==================== DATASET 21 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,1000,1000,49,11,1,599,61,1000,NaN,NaN

                      ==================== DATASET 22 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,999,1000,47,8,1,610,61,1000,NaN,NaN

                      ==================== DATASET 23 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,1000,1000,48,8,1,632,61,1000,NaN,NaN

                      ==================== DATASET 24 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,1000.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,1000,1000,49,11,1,603,61,1000,NaN,NaN

                      ==================== DATASET 25 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,104.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,1000,1000,29,8,2,231,45,382,NaN,NaN

                      ==================== DATASET 26 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,0.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,999,1000,2,1,1,422,59,1000,NaN,NaN

                      ==================== DATASET 27 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,0.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,1000,1000,1,1,1,106,4,1000,NaN,NaN

                      ==================== DATASET 28 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,0.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,1000,1000,1,1,1,188,12,1000,NaN,NaN

                      ==================== DATASET 29 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,0.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,997,999,4,1,1,637,61,999,NaN,NaN

                      ==================== DATASET 30 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,0.0,1000,1000,1000,1000,1000,1000,1000,999,0.0,0.0
unique,NaN,997,1000,7,1,1,750,61,998,NaN,NaN

                      ==================== DATASET 31 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,0.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,997,1000,8,2,1,528,61,1000,NaN,NaN

                      ==================== DATASET 32 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,0.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,995,1000,9,2,1,627,61,1000,NaN,NaN

                      ==================== DATASET 33 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,0.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,995,999,13,2,1,695,61,999,NaN,NaN

                      ==================== DATASET 34 ====================
Shape: (1000, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,0.0,1000,1000,1000,1000,1000,1000,1000,1000,0.0,0.0
unique,NaN,990,996,23,4,1,717,61,996,NaN,NaN

                      ==================== DATASET 35 ====================
Shape: (435, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,0.0,435,435,435,435,435,435,435,435,435,431
unique,NaN,431,435,20,7,1,369,61,435,435,431

In [5]:
df = ppr.fusion_dataset(dataset_list)
print(f"Shape: {df.shape}")
display(df.describe(include='all').loc[['count', 'unique']])

Shape: (34435, 11)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
count,24104.0,34434,34435,34435,34435,34435,34435,34435,34433,435,431
unique,NaN,33569,34377,56,13,2,1815,61,33264,435,431

### Data Cleaning

### Visualization

In [ ]:
dataset_list = read_dataset()

### Conclusion

My conclusion

# Next